### ISSUE TITLE
Add ability to dismiss warning about license for 24 hours

### ISSUE THREAD

**Issue by Mashenka** [UsabilityDynamics/lib-wp-bootstrap#2]
warning should be dismissed and page shouldn't be reloaded
![image](https://cloud.githubusercontent.com/assets/5111163/14639361/06cda6de-0645-11e6-8bb3-9c45a7abc13e.png)

**Comment by pemaxim** [comment]
I approved pull request and added new release. Everything looks good. 
I updated `wp-property` and `wp-property-terms` plugins with the latest `lib-wp-bootstrap` version.

##### Test and QA

@Mashenka do QA using `wp-property` and `wp-property-terms` ( `latest` branches ).
Be sure, that all other UD plugins and themes are disabled ( since they are using old `lib-wp-bootstrap` version )! If everything is fine, - finish the list of subtasks: to upgrade all other UD plugins and themes which are using `lib-wp-bootstrap` library ( I already added a few ones below ).

##### Subtasks

@mehulkaklotar complete the subtasks below when @Mashenka will be done with QA:
- [x] Upgrade [WP-Invoice](https://github.com/wp-invoice/wp-invoice)
- [x] Upgrade [wp-invoice-paypal-pro](https://github.com/wp-invoice/wp-invoice-paypal-pro)
- [x] Upgrade [wp-invoice-usa-epay](https://github.com/wp-invoice/wp-invoice-usa-epay)
- [x] Upgrade [wp-invoice-business-locations](https://github.com/wp-invoice/wp-invoice-business-locations)
- [x] Upgrade [wp-invoice-power-tools](https://github.com/wp-invoice/wp-invoice-power-tools)
- [x] Upgrade [wp-invoice-spc](https://github.com/wp-invoice/wp-invoice-spc) 
- [x] Upgrade [wp-invoice-quotes](https://github.com/wp-invoice/wp-invoice-quotes)
- [x] Upgrade [wp-invoice-electronic-signature](https://github.com/wp-invoice/wp-invoice-electronic-signature)
- [x] Upgrade [wp-invoice-pdf](https://github.com/wp-invoice/wp-invoice-pdf)
- [x] Upgrade [WP-CRM](https://github.com/wp-crm/wp-crm)
- [x] Upgrade [wp-crm-group-messages](https://github.com/wp-crm/wp-crm-group-messages)
- [x] Upgrade [Denali](https://github.com/wp-property/wp-denali)
- [x] Upgrade [Madison](https://github.com/wp-property/wp-madison)
- [x] Upgrade [WP-Property Agents](https://github.com/wp-property/wp-property-agents)
- [x] Upgrade [wp-property-responsive-slideshow](https://github.com/wp-property/wp-property-responsive-slideshow)
- [x] Upgrade [wp-property-feps](https://github.com/wp-property/wp-property-feps)
- [x] Upgrade [wp-property-pdf](https://github.com/wp-property/wp-property-pdf)
- [x] Upgrade [wp-property-supermap](https://github.com/wp-property/wp-property-supermap)
- [x] Upgrade [wp-property-walkscore](wp-property-walkscore)
- [x] Upgrade [wp-property-importer](https://github.com/wp-property/wp-property-importer)
- [x] Upgrade [wp-property-power-tools](https://github.com/wp-property/wp-property-power-tools) 
- [x] [Upgrade wp-property-facebook-tabs](https://github.com/wp-property/wp-property-facebook-tabs) 
- [x] Upgrade [wp-property-slideshow](https://github.com/wp-property/wp-property-slideshow)
- [x] Upgrade [wp-stateless](https://github.com/wpCloud/wp-stateless)

##### Upgrade Instructions
- Install [Grunt](http://gruntjs.com/getting-started)
- Update `lib-wp-bootstrap` version to `1.2.0` in composer.json
- Run `grunt install`. It will remove vendor dir and install all dependencies with required version again.

**Comment by Mashenka** [comment]
@mehulkaklotar I have checked with wp-property and wp-property terms plugins on the site. But dismiss button didn't appear for me. You can also check by yourself on workspace

**Comment by mehulkaklotar** [comment]
@Mashenka I have upgraded all plugins and libs with composer.

**Comment by Mashenka** [comment]
can you check this link - https://workspace.uds.io/wp-admin/plugins.php?plugin_status=inactive

they appear only when I deactivating wp-crm plugin

![image](https://cloud.githubusercontent.com/assets/5111163/15147514/bd721ad4-16c9-11e6-897b-df126700efce.png)

**Comment by Mashenka** [comment]
Also did you add ajax for this warning
![image](https://cloud.githubusercontent.com/assets/5111163/15147541/e1c7ad7c-16c9-11e6-9800-43c321a9a570.png)

**Comment by mehulkaklotar** [comment]
@Mashenka 
Workspace should have all plugins updated to `latest` branch. Might be some plugins are not updated.

For the ajax warning for you mentioned - I haven't added for those warning types. Do we need to add ajax for them too?

**Comment by Mashenka** [comment]
yes, you need to add ajax to them too

I will check if there is an issue with some of plugin. But we have set up that all of them are latest on workspace

**Comment by mehulkaklotar** [comment]
okay. I will add ajax for them too.

**Comment by Mashenka** [comment]
I have checked -  all plugins are latest on the site

**Comment by mehulkaklotar** [comment]
@Mashenka 
check this plugins on site if they are on `latest` branch or not:
- [wp-invoice-spc](https://github.com/wp-invoice/wp-invoice-spc/)
- [wp-invoice-pdf](https://github.com/wp-invoice/wp-invoice-pdf/)
- [wp-property-availability]
